codecov:
  require_ci_to_pass: yes
  max_report_age: off
  token: a8c94fc0-6423-4424-b6d0-87e4ffc08924

coverage:
  precision: 2
  round: down
  range: 50..90
  status:
    project:
      default:
       enabled: no
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
